
modLoader="javafml" #mandatory

loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

issueTrackerURL="https://github.com/MehVahdJukaar/every_compat/issues" #optional

[[mods]] #mandatory

modId="everycomp" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Every Compat" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="https://www.curseforge.com/minecraft/mc-mods/every_compat" #optional

logoFile="logo.png" #optional

credits="Plantkillable, Frogbirdd, Pau_1eal" #optional

authors="MehVahdJukaar" #optional

description='''Ultimate Wood Compat Mod'''

itemIcon="minecraft:oak_planks" #catalogue icon


[[dependencies.everycomp]] #optional

    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40.0.36,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.everycomp]]

    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19]"
    ordering="NONE"
    side="BOTH"

[[dependencies.everycomp]]

    modId="selene"
    mandatory=true
    versionRange="[1.18.2-1.17.3,]"
    ordering="AFTER"
    side="BOTH"


